# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUiFiles/budgeter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BGBudgeter(object):
    def setupUi(self, BGBudgeter):
        BGBudgeter.setObjectName("BGBudgeter")
        BGBudgeter.resize(900, 600)
        self.stackedWidget = QtWidgets.QStackedWidget(BGBudgeter)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setStyleSheet("QPushButton {\n"
"    background-color: rgb(220,220,220);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200,200,200);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(210,200,220);\n"
"}\n"
"")
        self.mainPage.setObjectName("mainPage")
        self.mainPageTtl = QtWidgets.QLabel(self.mainPage)
        self.mainPageTtl.setGeometry(QtCore.QRect(0, 0, 900, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mainPageTtl.setFont(font)
        self.mainPageTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(250, 200, 50, 255), stop:1 rgba(255, 80, 100, 255));")
        self.mainPageTtl.setAlignment(QtCore.Qt.AlignCenter)
        self.mainPageTtl.setObjectName("mainPageTtl")
        self.mainPageInfoLbl = QtWidgets.QLabel(self.mainPage)
        self.mainPageInfoLbl.setGeometry(QtCore.QRect(25, 479, 850, 111))
        self.mainPageInfoLbl.setText("")
        self.mainPageInfoLbl.setObjectName("mainPageInfoLbl")
        self.incomePageButton = QtWidgets.QPushButton(self.mainPage)
        self.incomePageButton.setGeometry(QtCore.QRect(275, 80, 350, 80))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.incomePageButton.setFont(font)
        self.incomePageButton.setObjectName("incomePageButton")
        self.categoryPageButton = QtWidgets.QPushButton(self.mainPage)
        self.categoryPageButton.setGeometry(QtCore.QRect(275, 180, 350, 80))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.categoryPageButton.setFont(font)
        self.categoryPageButton.setObjectName("categoryPageButton")
        self.optionsPageButton = QtWidgets.QPushButton(self.mainPage)
        self.optionsPageButton.setGeometry(QtCore.QRect(275, 280, 350, 80))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.optionsPageButton.setFont(font)
        self.optionsPageButton.setObjectName("optionsPageButton")
        self.viewBudgetPageButton = QtWidgets.QPushButton(self.mainPage)
        self.viewBudgetPageButton.setGeometry(QtCore.QRect(275, 380, 350, 80))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.viewBudgetPageButton.setFont(font)
        self.viewBudgetPageButton.setObjectName("viewBudgetPageButton")
        self.stackedWidget.addWidget(self.mainPage)
        self.incomeInputPage = QtWidgets.QWidget()
        self.incomeInputPage.setObjectName("incomeInputPage")
        self.incomePageTtl = QtWidgets.QLabel(self.incomeInputPage)
        self.incomePageTtl.setGeometry(QtCore.QRect(0, 0, 900, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.incomePageTtl.setFont(font)
        self.incomePageTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(250, 200, 50, 255), stop:1 rgba(255, 80, 100, 255));")
        self.incomePageTtl.setAlignment(QtCore.Qt.AlignCenter)
        self.incomePageTtl.setObjectName("incomePageTtl")
        self.incomeSourcesScrollArea = QtWidgets.QScrollArea(self.incomeInputPage)
        self.incomeSourcesScrollArea.setGeometry(QtCore.QRect(10, 70, 880, 380))
        self.incomeSourcesScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.incomeSourcesScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.incomeSourcesScrollArea.setWidgetResizable(True)
        self.incomeSourcesScrollArea.setObjectName("incomeSourcesScrollArea")
        self.incomeScrollAreaContents = QtWidgets.QWidget()
        self.incomeScrollAreaContents.setGeometry(QtCore.QRect(0, 0, 857, 378))
        self.incomeScrollAreaContents.setObjectName("incomeScrollAreaContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.incomeScrollAreaContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.incomeSourceParentWidget = QtWidgets.QWidget(self.incomeScrollAreaContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incomeSourceParentWidget.sizePolicy().hasHeightForWidth())
        self.incomeSourceParentWidget.setSizePolicy(sizePolicy)
        self.incomeSourceParentWidget.setMinimumSize(QtCore.QSize(835, 100))
        self.incomeSourceParentWidget.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.incomeSourceParentWidget.setObjectName("incomeSourceParentWidget")
        self.incomeAmountSpinBox = QtWidgets.QDoubleSpinBox(self.incomeSourceParentWidget)
        self.incomeAmountSpinBox.setGeometry(QtCore.QRect(5, 35, 140, 50))
        self.incomeAmountSpinBox.setStyleSheet("border-style: solid;\n"
"border-color: black;\n"
"border-radius: 5px;\n"
"border-width: 1px;\n"
"background-color: rgb(250,250,250);\n"
"")
        self.incomeAmountSpinBox.setMaximum(1000000.0)
        self.incomeAmountSpinBox.setProperty("value", 30000.0)
        self.incomeAmountSpinBox.setObjectName("incomeAmountSpinBox")
        self.incomeAmountLbl = QtWidgets.QLabel(self.incomeSourceParentWidget)
        self.incomeAmountLbl.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(8)
        self.incomeAmountLbl.setFont(font)
        self.incomeAmountLbl.setObjectName("incomeAmountLbl")
        self.incomePeriodComboBox = QtWidgets.QComboBox(self.incomeSourceParentWidget)
        self.incomePeriodComboBox.setGeometry(QtCore.QRect(280, 35, 151, 50))
        self.incomePeriodComboBox.setStyleSheet("border-style: solid;\n"
"border-color: black;\n"
"border-radius: 5px;\n"
"border-width: 1px;\n"
"background-color: white;\n"
"")
        self.incomePeriodComboBox.setObjectName("incomePeriodComboBox")
        self.incomePeriodComboBox.addItem("")
        self.incomePeriodComboBox.addItem("")
        self.incomePeriodComboBox.addItem("")
        self.incomePeriodComboBox.addItem("")
        self.incomePeriodComboBox.addItem("")
        self.incomeAdd100Button = QtWidgets.QPushButton(self.incomeSourceParentWidget)
        self.incomeAdd100Button.setGeometry(QtCore.QRect(160, 35, 50, 25))
        self.incomeAdd100Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(75,175,0);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,155,0);\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(15,135,0);\n"
"\n"
"}")
        self.incomeAdd100Button.setObjectName("incomeAdd100Button")
        self.incomeMinus100Button = QtWidgets.QPushButton(self.incomeSourceParentWidget)
        self.incomeMinus100Button.setGeometry(QtCore.QRect(160, 60, 50, 25))
        self.incomeMinus100Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250,175,0);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230,155,0);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(210,135,0);\n"
"\n"
"}")
        self.incomeMinus100Button.setObjectName("incomeMinus100Button")
        self.incomeAdd1000Button = QtWidgets.QPushButton(self.incomeSourceParentWidget)
        self.incomeAdd1000Button.setGeometry(QtCore.QRect(210, 35, 50, 25))
        self.incomeAdd1000Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(125,225,0);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(105,205,0);\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85,185,0);\n"
"\n"
"}")
        self.incomeAdd1000Button.setObjectName("incomeAdd1000Button")
        self.incomeMinus1000Button = QtWidgets.QPushButton(self.incomeSourceParentWidget)
        self.incomeMinus1000Button.setGeometry(QtCore.QRect(210, 60, 50, 25))
        self.incomeMinus1000Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250,100,0);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230,80,0);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(210,60,0);\n"
"\n"
"}")
        self.incomeMinus1000Button.setObjectName("incomeMinus1000Button")
        self.incomePeriodLbl = QtWidgets.QLabel(self.incomeSourceParentWidget)
        self.incomePeriodLbl.setGeometry(QtCore.QRect(280, 10, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(8)
        self.incomePeriodLbl.setFont(font)
        self.incomePeriodLbl.setObjectName("incomePeriodLbl")
        self.incomeOccurencesSpinBox = QtWidgets.QSpinBox(self.incomeSourceParentWidget)
        self.incomeOccurencesSpinBox.setGeometry(QtCore.QRect(470, 40, 111, 41))
        self.incomeOccurencesSpinBox.setStyleSheet("border-style: solid;\n"
"border-color: black;\n"
"border-radius: 5px;\n"
"border-width: 1px;\n"
"background-color: rgb(250,250,250);\n"
"")
        self.incomeOccurencesSpinBox.setProperty("value", 50)
        self.incomeOccurencesSpinBox.setObjectName("incomeOccurencesSpinBox")
        self.incomeOccurencesLbl = QtWidgets.QLabel(self.incomeSourceParentWidget)
        self.incomeOccurencesLbl.setGeometry(QtCore.QRect(470, 10, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(8)
        self.incomeOccurencesLbl.setFont(font)
        self.incomeOccurencesLbl.setObjectName("incomeOccurencesLbl")
        self.pushButton = QtWidgets.QPushButton(self.incomeSourceParentWidget)
        self.pushButton.setGeometry(QtCore.QRect(740, 10, 80, 80))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(30,30,30);\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(210,0,0);\n"
"    border-color: rgb(15,15,15);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170,0,0);\n"
"    border-color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.incomeSourceParentWidget)
        self.incomeSourcesScrollArea.setWidget(self.incomeScrollAreaContents)
        self.incomeBackButton = QtWidgets.QPushButton(self.incomeInputPage)
        self.incomeBackButton.setGeometry(QtCore.QRect(5, 5, 50, 50))
        self.incomeBackButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250,100,0);\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(50,50,50);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(225,75,0);\n"
"    border-color: rgb(25,25,25);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200,50,0);\n"
"    border-color: black;\n"
"}\n"
"")
        self.incomeBackButton.setObjectName("incomeBackButton")
        self.addIncomeButton = QtWidgets.QPushButton(self.incomeInputPage)
        self.addIncomeButton.setGeometry(QtCore.QRect(750, 460, 140, 47))
        self.addIncomeButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0,220,100);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(30,30,30);\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,200,80);\n"
"    border-color: rgb(15,15,15);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0,180,60);\n"
"    border-color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.addIncomeButton.setObjectName("addIncomeButton")
        self.updateIncomeButton = QtWidgets.QPushButton(self.incomeInputPage)
        self.updateIncomeButton.setGeometry(QtCore.QRect(375, 520, 150, 50))
        self.updateIncomeButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250,180,0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(30,30,30);\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230,160,0);\n"
"    border-color: rgb(15,15,15);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(210,140,0);\n"
"    border-color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.updateIncomeButton.setObjectName("updateIncomeButton")
        self.incomeTipsLbl = QtWidgets.QLabel(self.incomeInputPage)
        self.incomeTipsLbl.setGeometry(QtCore.QRect(20, 460, 281, 111))
        self.incomeTipsLbl.setObjectName("incomeTipsLbl")
        self.stackedWidget.addWidget(self.incomeInputPage)
        self.categoryPage = QtWidgets.QWidget()
        self.categoryPage.setObjectName("categoryPage")
        self.categoryPageTtl = QtWidgets.QLabel(self.categoryPage)
        self.categoryPageTtl.setGeometry(QtCore.QRect(0, 0, 900, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.categoryPageTtl.setFont(font)
        self.categoryPageTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(250, 200, 50, 255), stop:1 rgba(255, 80, 100, 255));")
        self.categoryPageTtl.setAlignment(QtCore.Qt.AlignCenter)
        self.categoryPageTtl.setObjectName("categoryPageTtl")
        self.categoryBackButton = QtWidgets.QPushButton(self.categoryPage)
        self.categoryBackButton.setGeometry(QtCore.QRect(5, 5, 50, 50))
        self.categoryBackButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250,100,0);\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(50,50,50);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(225,75,0);\n"
"    border-color: rgb(25,25,25);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200,50,0);\n"
"    border-color: black;\n"
"}\n"
"")
        self.categoryBackButton.setObjectName("categoryBackButton")
        self.categoryTable = QtWidgets.QTableWidget(self.categoryPage)
        self.categoryTable.setGeometry(QtCore.QRect(10, 120, 880, 470))
        self.categoryTable.setObjectName("categoryTable")
        self.categoryTable.setColumnCount(0)
        self.categoryTable.setRowCount(0)
        self.categoryNameInputLE = QtWidgets.QLineEdit(self.categoryPage)
        self.categoryNameInputLE.setGeometry(QtCore.QRect(10, 65, 281, 50))
        self.categoryNameInputLE.setObjectName("categoryNameInputLE")
        self.addCategoryButton = QtWidgets.QPushButton(self.categoryPage)
        self.addCategoryButton.setGeometry(QtCore.QRect(730, 65, 160, 40))
        self.addCategoryButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100,200,100);\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(50,50,50);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85,185,85);\n"
"    border-color: rgb(25,25,25);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(60,160,60);\n"
"    border-color: black;\n"
"}\n"
"")
        self.addCategoryButton.setObjectName("addCategoryButton")
        self.categoryAmountSpinBox = QtWidgets.QDoubleSpinBox(self.categoryPage)
        self.categoryAmountSpinBox.setGeometry(QtCore.QRect(415, 65, 110, 50))
        self.categoryAmountSpinBox.setMaximum(1000000000.0)
        self.categoryAmountSpinBox.setProperty("value", 50.0)
        self.categoryAmountSpinBox.setObjectName("categoryAmountSpinBox")
        self.expenseAmountLbl = QtWidgets.QLabel(self.categoryPage)
        self.expenseAmountLbl.setGeometry(QtCore.QRect(295, 70, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.expenseAmountLbl.setFont(font)
        self.expenseAmountLbl.setObjectName("expenseAmountLbl")
        self.plus10Button = QtWidgets.QPushButton(self.categoryPage)
        self.plus10Button.setGeometry(QtCore.QRect(530, 70, 50, 20))
        self.plus10Button.setObjectName("plus10Button")
        self.minus10Button = QtWidgets.QPushButton(self.categoryPage)
        self.minus10Button.setGeometry(QtCore.QRect(530, 90, 50, 20))
        self.minus10Button.setObjectName("minus10Button")
        self.plus100Button = QtWidgets.QPushButton(self.categoryPage)
        self.plus100Button.setGeometry(QtCore.QRect(580, 70, 50, 20))
        self.plus100Button.setObjectName("plus100Button")
        self.minus100Button = QtWidgets.QPushButton(self.categoryPage)
        self.minus100Button.setGeometry(QtCore.QRect(580, 90, 50, 20))
        self.minus100Button.setObjectName("minus100Button")
        self.stackedWidget.addWidget(self.categoryPage)
        self.optionsPage = QtWidgets.QWidget()
        self.optionsPage.setObjectName("optionsPage")
        self.optionsPageTtl = QtWidgets.QLabel(self.optionsPage)
        self.optionsPageTtl.setGeometry(QtCore.QRect(0, 0, 900, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.optionsPageTtl.setFont(font)
        self.optionsPageTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(250, 200, 50, 255), stop:1 rgba(255, 80, 100, 255));")
        self.optionsPageTtl.setAlignment(QtCore.Qt.AlignCenter)
        self.optionsPageTtl.setObjectName("optionsPageTtl")
        self.optionsBackButton = QtWidgets.QPushButton(self.optionsPage)
        self.optionsBackButton.setGeometry(QtCore.QRect(5, 5, 50, 50))
        self.optionsBackButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250,100,0);\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(50,50,50);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(225,75,0);\n"
"    border-color: rgb(25,25,25);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200,50,0);\n"
"    border-color: black;\n"
"}\n"
"")
        self.optionsBackButton.setObjectName("optionsBackButton")
        self.weeklyBudgetRadioButton = QtWidgets.QRadioButton(self.optionsPage)
        self.weeklyBudgetRadioButton.setGeometry(QtCore.QRect(20, 100, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.weeklyBudgetRadioButton.setFont(font)
        self.weeklyBudgetRadioButton.setObjectName("weeklyBudgetRadioButton")
        self.fortnightlyBudgetRadioButton = QtWidgets.QRadioButton(self.optionsPage)
        self.fortnightlyBudgetRadioButton.setGeometry(QtCore.QRect(20, 125, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.fortnightlyBudgetRadioButton.setFont(font)
        self.fortnightlyBudgetRadioButton.setObjectName("fortnightlyBudgetRadioButton")
        self.timePeriodOptionLbl = QtWidgets.QLabel(self.optionsPage)
        self.timePeriodOptionLbl.setGeometry(QtCore.QRect(10, 70, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.timePeriodOptionLbl.setFont(font)
        self.timePeriodOptionLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.timePeriodOptionLbl.setObjectName("timePeriodOptionLbl")
        self.monthlyBudgetRadioButton = QtWidgets.QRadioButton(self.optionsPage)
        self.monthlyBudgetRadioButton.setGeometry(QtCore.QRect(20, 150, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.monthlyBudgetRadioButton.setFont(font)
        self.monthlyBudgetRadioButton.setObjectName("monthlyBudgetRadioButton")
        self.stackedWidget.addWidget(self.optionsPage)
        self.viewBudgetPage = QtWidgets.QWidget()
        self.viewBudgetPage.setObjectName("viewBudgetPage")
        self.viewBudgetPageTtl = QtWidgets.QLabel(self.viewBudgetPage)
        self.viewBudgetPageTtl.setGeometry(QtCore.QRect(0, 0, 900, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.viewBudgetPageTtl.setFont(font)
        self.viewBudgetPageTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(250, 200, 50, 255), stop:1 rgba(255, 80, 100, 255));")
        self.viewBudgetPageTtl.setAlignment(QtCore.Qt.AlignCenter)
        self.viewBudgetPageTtl.setObjectName("viewBudgetPageTtl")
        self.viewBudgetBackButton = QtWidgets.QPushButton(self.viewBudgetPage)
        self.viewBudgetBackButton.setGeometry(QtCore.QRect(5, 5, 50, 50))
        self.viewBudgetBackButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250,100,0);\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(50,50,50);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(225,75,0);\n"
"    border-color: rgb(25,25,25);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200,50,0);\n"
"    border-color: black;\n"
"}\n"
"")
        self.viewBudgetBackButton.setObjectName("viewBudgetBackButton")
        self.budgetTable = QtWidgets.QTableWidget(self.viewBudgetPage)
        self.budgetTable.setGeometry(QtCore.QRect(10, 70, 880, 450))
        self.budgetTable.setObjectName("budgetTable")
        self.budgetTable.setColumnCount(0)
        self.budgetTable.setRowCount(0)
        self.stackedWidget.addWidget(self.viewBudgetPage)

        self.retranslateUi(BGBudgeter)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BGBudgeter)

    def retranslateUi(self, BGBudgeter):
        _translate = QtCore.QCoreApplication.translate
        BGBudgeter.setWindowTitle(_translate("BGBudgeter", "BG-Budgeter"))
        self.mainPageTtl.setText(_translate("BGBudgeter", "BG-Budgeter"))
        self.incomePageButton.setText(_translate("BGBudgeter", "Income"))
        self.categoryPageButton.setText(_translate("BGBudgeter", "Expense Category Settings"))
        self.optionsPageButton.setText(_translate("BGBudgeter", "Extra Options"))
        self.viewBudgetPageButton.setText(_translate("BGBudgeter", "View Budget"))
        self.incomePageTtl.setText(_translate("BGBudgeter", "BG-Budgeter  -  Choose Your Income Sources"))
        self.incomeAmountLbl.setText(_translate("BGBudgeter", "Income Amount:"))
        self.incomePeriodComboBox.setItemText(0, _translate("BGBudgeter", "Weekly"))
        self.incomePeriodComboBox.setItemText(1, _translate("BGBudgeter", "Fortnightly"))
        self.incomePeriodComboBox.setItemText(2, _translate("BGBudgeter", "Monthly"))
        self.incomePeriodComboBox.setItemText(3, _translate("BGBudgeter", "Annually"))
        self.incomePeriodComboBox.setItemText(4, _translate("BGBudgeter", "Student Maintenance Loan (UK)"))
        self.incomeAdd100Button.setText(_translate("BGBudgeter", "+100"))
        self.incomeMinus100Button.setText(_translate("BGBudgeter", "-100"))
        self.incomeAdd1000Button.setText(_translate("BGBudgeter", "+1000"))
        self.incomeMinus1000Button.setText(_translate("BGBudgeter", "-1000"))
        self.incomePeriodLbl.setText(_translate("BGBudgeter", "Pay Period/Cycle Length:"))
        self.incomeOccurencesLbl.setText(_translate("BGBudgeter", "How Many Times Per Year Are You Paid?"))
        self.pushButton.setText(_translate("BGBudgeter", "REMOVE"))
        self.incomeBackButton.setText(_translate("BGBudgeter", "BACK"))
        self.addIncomeButton.setText(_translate("BGBudgeter", "Add Income Source"))
        self.updateIncomeButton.setText(_translate("BGBudgeter", "UPDATE"))
        self.incomeTipsLbl.setText(_translate("BGBudgeter", "Tips:\n"
"- You can manually enter an amount into the\n"
"  income amount option box\n"
"- The occurences option details how many\n"
"  times per year you are paid. For example,\n"
"  200 a week 50 times a year is a yearly\n"
"  income total of 10000"))
        self.categoryPageTtl.setText(_translate("BGBudgeter", "BG-Budgeter  -  Choose Your Expense Categories"))
        self.categoryBackButton.setText(_translate("BGBudgeter", "BACK"))
        self.categoryNameInputLE.setPlaceholderText(_translate("BGBudgeter", "Expense Name"))
        self.addCategoryButton.setText(_translate("BGBudgeter", "ADD"))
        self.expenseAmountLbl.setText(_translate("BGBudgeter", "Expense Amount:"))
        self.plus10Button.setText(_translate("BGBudgeter", "+10"))
        self.minus10Button.setText(_translate("BGBudgeter", "-10"))
        self.plus100Button.setText(_translate("BGBudgeter", "+100"))
        self.minus100Button.setText(_translate("BGBudgeter", "-100"))
        self.optionsPageTtl.setText(_translate("BGBudgeter", "BG-Budgeter  -  Extra Options"))
        self.optionsBackButton.setText(_translate("BGBudgeter", "BACK"))
        self.weeklyBudgetRadioButton.setText(_translate("BGBudgeter", "Weekly"))
        self.fortnightlyBudgetRadioButton.setText(_translate("BGBudgeter", "Fortnightly"))
        self.timePeriodOptionLbl.setText(_translate("BGBudgeter", "Budget Time Period"))
        self.monthlyBudgetRadioButton.setText(_translate("BGBudgeter", "Monthly"))
        self.viewBudgetPageTtl.setText(_translate("BGBudgeter", "BG-Budgeter  -  View Your Budget"))
        self.viewBudgetBackButton.setText(_translate("BGBudgeter", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BGBudgeter = QtWidgets.QDialog()
    ui = Ui_BGBudgeter()
    ui.setupUi(BGBudgeter)
    BGBudgeter.show()
    sys.exit(app.exec_())
