# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BGBudgeter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BGBudgeterClass(object):
    def setupUi(self, BGBudgeterClass):
        BGBudgeterClass.setObjectName("BGBudgeterClass")
        BGBudgeterClass.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(BGBudgeterClass)
        self.centralWidget.setObjectName("centralWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.stackedWidget.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        self.mainPage.setFont(font)
        self.mainPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mainPage.setStyleSheet("QPushButton {\n"
"    background-color: rgb(220,220,220);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200,200,200);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(210,200,220);\n"
"}\n"
"")
        self.mainPage.setObjectName("mainPage")
        self.mainTtl = QtWidgets.QLabel(self.mainPage)
        self.mainTtl.setGeometry(QtCore.QRect(0, 0, 800, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(21)
        font.setBold(True)
        self.mainTtl.setFont(font)
        self.mainTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.75, y2:0.75, stop:0 rgba(0, 100, 255, 255), stop:1 rgba(200, 0, 255, 205));")
        self.mainTtl.setAlignment(QtCore.Qt.Q.AlignmentFlag.AlignCenter)
        self.mainTtl.setObjectName("mainTtl")
        self.incomePageButton = QtWidgets.QPushButton(self.mainPage)
        self.incomePageButton.setGeometry(QtCore.QRect(200, 70, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.incomePageButton.setFont(font)
        self.incomePageButton.setCheckable(False)
        self.incomePageButton.setObjectName("incomePageButton")
        self.categoryPageButton = QtWidgets.QPushButton(self.mainPage)
        self.categoryPageButton.setGeometry(QtCore.QRect(200, 180, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.categoryPageButton.setFont(font)
        self.categoryPageButton.setCheckable(False)
        self.categoryPageButton.setObjectName("categoryPageButton")
        self.optionsPageButton = QtWidgets.QPushButton(self.mainPage)
        self.optionsPageButton.setGeometry(QtCore.QRect(200, 290, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.optionsPageButton.setFont(font)
        self.optionsPageButton.setCheckable(False)
        self.optionsPageButton.setObjectName("optionsPageButton")
        self.viewBudgetPageButton = QtWidgets.QPushButton(self.mainPage)
        self.viewBudgetPageButton.setGeometry(QtCore.QRect(200, 400, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.viewBudgetPageButton.setFont(font)
        self.viewBudgetPageButton.setCheckable(False)
        self.viewBudgetPageButton.setObjectName("viewBudgetPageButton")
        self.mainPageInfoLbl = QtWidgets.QLabel(self.mainPage)
        self.mainPageInfoLbl.setGeometry(QtCore.QRect(70, 520, 661, 51))
        self.mainPageInfoLbl.setText("")
        self.mainPageInfoLbl.setObjectName("mainPageInfoLbl")
        self.testButton = QtWidgets.QPushButton(self.mainPage)
        self.testButton.setGeometry(QtCore.QRect(30, 220, 51, 61))
        self.testButton.setObjectName("testButton")
        self.stackedWidget.addWidget(self.mainPage)
        self.incomeSetPage = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.incomeSetPage.setFont(font)
        self.incomeSetPage.setObjectName("incomeSetPage")
        self.incomeSetTtl = QtWidgets.QLabel(self.incomeSetPage)
        self.incomeSetTtl.setGeometry(QtCore.QRect(0, 0, 800, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(21)
        font.setBold(True)
        self.incomeSetTtl.setFont(font)
        self.incomeSetTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.75, y2:0.75, stop:0 rgba(0, 100, 255, 255), stop:1 rgba(200, 0, 255, 205));")
        self.incomeSetTtl.setAlignment(QtCore.Qt.Qt.AlignmentFlag.AlignCenter)
        self.incomeSetTtl.setObjectName("incomeSetTtl")
        self.incomeInfoLbl1 = QtWidgets.QLabel(self.incomeSetPage)
        self.incomeInfoLbl1.setGeometry(QtCore.QRect(20, 50, 760, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        self.incomeInfoLbl1.setFont(font)
        self.incomeInfoLbl1.setWordWrap(True)
        self.incomeInfoLbl1.setObjectName("incomeInfoLbl1")
        self.scrollArea = QtWidgets.QScrollArea(self.incomeSetPage)
        self.scrollArea.setGeometry(QtCore.QRect(10, 80, 780, 360))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 778, 358))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.incomeWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.incomeWidget.setGeometry(QtCore.QRect(0, 0, 750, 80))
        self.incomeWidget.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(200,200,200);")
        self.incomeWidget.setObjectName("incomeWidget")
        self.incomeInputLE = QtWidgets.QLineEdit(self.incomeWidget)
        self.incomeInputLE.setGeometry(QtCore.QRect(20, 25, 200, 30))
        self.incomeInputLE.setStyleSheet("border: 1px solid black;\n"
"background-color: white;\n"
"border-radius:5px;")
        self.incomeInputLE.setObjectName("incomeInputLE")
        self.incomePeriodComboBox = QtWidgets.QComboBox(self.incomeWidget)
        self.incomePeriodComboBox.setGeometry(QtCore.QRect(240, 25, 200, 30))
        self.incomePeriodComboBox.setStyleSheet("border: 1px solid black;\n"
"background-color: white;\n"
"border-radius: 5px;")
        self.incomePeriodComboBox.setObjectName("incomePeriodComboBox")
        self.incomePeriodComboBox.addItem("")
        self.incomePeriodComboBox.addItem("")
        self.incomePeriodComboBox.addItem("")
        self.incomePeriodComboBox.addItem("")
        self.payOccurencesPerYear = QtWidgets.QSpinBox(self.incomeWidget)
        self.payOccurencesPerYear.setGeometry(QtCore.QRect(520, 25, 80, 30))
        self.payOccurencesPerYear.setStyleSheet("border: 1px solid black;\n"
"background-color: white;\n"
"border-radius:  5px;")
        self.payOccurencesPerYear.setMaximum(52)
        self.payOccurencesPerYear.setProperty("value", 52)
        self.payOccurencesPerYear.setObjectName("payOccurencesPerYear")
        self.removeButton = QtWidgets.QPushButton(self.incomeWidget)
        self.removeButton.setGeometry(QtCore.QRect(660, 30, 75, 24))
        self.removeButton.setStyleSheet("border: 1px solid black;\n"
"border-radius: 5px;\n"
"background-color: rgb(200,40,40);")
        self.removeButton.setObjectName("removeButton")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.addIncomeButton = QtWidgets.QPushButton(self.incomeSetPage)
        self.addIncomeButton.setGeometry(QtCore.QRect(640, 450, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.addIncomeButton.setFont(font)
        self.addIncomeButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0,160,200);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,85,95);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,140,180);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,55,65);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 120, 160);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,45,55);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"")
        self.addIncomeButton.setObjectName("addIncomeButton")
        self.updateIncomeButton = QtWidgets.QPushButton(self.incomeSetPage)
        self.updateIncomeButton.setGeometry(QtCore.QRect(325, 550, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.updateIncomeButton.setFont(font)
        self.updateIncomeButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0,150,110);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,75,65);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,130,90);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,45,35);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0,110,70);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,35,25);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"")
        self.updateIncomeButton.setObjectName("updateIncomeButton")
        self.backButtonIncomePage = QtWidgets.QPushButton(self.incomeSetPage)
        self.backButtonIncomePage.setGeometry(QtCore.QRect(5, 5, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.backButtonIncomePage.setFont(font)
        self.backButtonIncomePage.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100,150,250);\n"
"    border-style: solid;\n"
"    border-color: rgb(50,50,50);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(90,140,240);\n"
"    border-style: solid;\n"
"    border-color: rgb(30,30,30);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70,120,220);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"")
        self.backButtonIncomePage.setObjectName("backButtonIncomePage")
        self.stackedWidget.addWidget(self.incomeSetPage)
        self.categoryPage = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        self.categoryPage.setFont(font)
        self.categoryPage.setObjectName("categoryPage")
        self.categoryTtl = QtWidgets.QLabel(self.categoryPage)
        self.categoryTtl.setGeometry(QtCore.QRect(0, 0, 800, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(21)
        font.setBold(True)
        self.categoryTtl.setFont(font)
        self.categoryTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.75, y2:0.75, stop:0 rgba(0, 100, 255, 255), stop:1 rgba(200, 0, 255, 205));")
        self.categoryTtl.setAlignment(QtCore.Qt.Qt.AlignmentFlag.AlignCenter)
        self.categoryTtl.setObjectName("categoryTtl")
        self.categoryTable = QtWidgets.QTableWidget(self.categoryPage)
        self.categoryTable.setGeometry(QtCore.QRect(0, 100, 800, 410))
        self.categoryTable.setObjectName("categoryTable")
        self.categoryTable.setColumnCount(0)
        self.categoryTable.setRowCount(0)
        self.categoryInputLE = QtWidgets.QLineEdit(self.categoryPage)
        self.categoryInputLE.setGeometry(QtCore.QRect(10, 60, 700, 30))
        self.categoryInputLE.setObjectName("categoryInputLE")
        self.addCategoryButton = QtWidgets.QPushButton(self.categoryPage)
        self.addCategoryButton.setGeometry(QtCore.QRect(720, 60, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(11)
        font.setBold(False)
        self.addCategoryButton.setFont(font)
        self.addCategoryButton.setStyleSheet("background-color: rgb(6, 181, 114);\n"
"border-radius: 5px;")
        self.addCategoryButton.setObjectName("addCategoryButton")
        self.categoryTipsLbl = QtWidgets.QLabel(self.categoryPage)
        self.categoryTipsLbl.setGeometry(QtCore.QRect(10, 520, 780, 80))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        self.categoryTipsLbl.setFont(font)
        self.categoryTipsLbl.setAlignment(QtCore.Qt.Qt.AlignmentFlag.AlignCenter)
        self.categoryTipsLbl.setObjectName("categoryTipsLbl")
        self.backButtonCategoryPage = QtWidgets.QPushButton(self.categoryPage)
        self.backButtonCategoryPage.setGeometry(QtCore.QRect(5, 5, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.backButtonCategoryPage.setFont(font)
        self.backButtonCategoryPage.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100,150,250);\n"
"    border-style: solid;\n"
"    border-color: rgb(50,50,50);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(90,140,240);\n"
"    border-style: solid;\n"
"    border-color: rgb(30,30,30);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70,120,220);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"")
        self.backButtonCategoryPage.setObjectName("backButtonCategoryPage")
        self.stackedWidget.addWidget(self.categoryPage)
        self.optionsPage = QtWidgets.QWidget()
        self.optionsPage.setObjectName("optionsPage")
        self.otherOptionsTtl = QtWidgets.QLabel(self.optionsPage)
        self.otherOptionsTtl.setGeometry(QtCore.QRect(0, 0, 800, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(21)
        font.setBold(True)
        self.otherOptionsTtl.setFont(font)
        self.otherOptionsTtl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.75, y2:0.75, stop:0 rgba(0, 100, 255, 255), stop:1 rgba(200, 0, 255, 205));")
        self.otherOptionsTtl.setAlignment(QtCore.Qt.Qt.AlignmentFlag.AlignCenter)
        self.otherOptionsTtl.setObjectName("otherOptionsTtl")
        self.backButtonOptionsPage = QtWidgets.QPushButton(self.optionsPage)
        self.backButtonOptionsPage.setGeometry(QtCore.QRect(5, 5, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.backButtonOptionsPage.setFont(font)
        self.backButtonOptionsPage.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100,150,250);\n"
"    border-style: solid;\n"
"    border-color: rgb(50,50,50);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(90,140,240);\n"
"    border-style: solid;\n"
"    border-color: rgb(30,30,30);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70,120,220);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"")
        self.backButtonOptionsPage.setObjectName("backButtonOptionsPage")
        self.stackedWidget.addWidget(self.optionsPage)
        self.viewBudgetPage = QtWidgets.QWidget()
        self.viewBudgetPage.setObjectName("viewBudgetPage")
        self.otherOptionsTtl_2 = QtWidgets.QLabel(self.viewBudgetPage)
        self.otherOptionsTtl_2.setGeometry(QtCore.QRect(0, 0, 800, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(21)
        font.setBold(True)
        self.otherOptionsTtl_2.setFont(font)
        self.otherOptionsTtl_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.75, y2:0.75, stop:0 rgba(0, 100, 255, 255), stop:1 rgba(200, 0, 255, 205));")
        self.otherOptionsTtl_2.setAlignment(QtCore.Qt.Qt.AlignmentFlag.AlignCenter)
        self.otherOptionsTtl_2.setObjectName("otherOptionsTtl_2")
        self.backButtonViewBudgetPage = QtWidgets.QPushButton(self.viewBudgetPage)
        self.backButtonViewBudgetPage.setGeometry(QtCore.QRect(0, 0, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.backButtonViewBudgetPage.setFont(font)
        self.backButtonViewBudgetPage.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100,150,250);\n"
"    border-style: solid;\n"
"    border-color: rgb(50,50,50);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(90,140,240);\n"
"    border-style: solid;\n"
"    border-color: rgb(30,30,30);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70,120,220);\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"    border-radius: 6px;\n"
"    border-width: 2px;\n"
"}\n"
"")
        self.backButtonViewBudgetPage.setObjectName("backButtonViewBudgetPage")
        self.stackedWidget.addWidget(self.viewBudgetPage)
        BGBudgeterClass.setCentralWidget(self.centralWidget)

        self.retranslateUi(BGBudgeterClass)
        QtCore.QMetaObject.connectSlotsByName(BGBudgeterClass)

    def retranslateUi(self, BGBudgeterClass):
        _translate = QtCore.QCoreApplication.translate
        BGBudgeterClass.setWindowTitle(_translate("BGBudgeterClass", "BGBudgeter"))
        self.mainTtl.setText(_translate("BGBudgeterClass", "BG Budgeter - Home"))
        self.incomePageButton.setText(_translate("BGBudgeterClass", "Income Settings"))
        self.categoryPageButton.setText(_translate("BGBudgeterClass", "Expense and Savings Category Settings"))
        self.optionsPageButton.setText(_translate("BGBudgeterClass", "Other Budget Options"))
        self.viewBudgetPageButton.setText(_translate("BGBudgeterClass", "View Budget"))
        self.testButton.setText(_translate("BGBudgeterClass", "Test"))
        self.incomeSetTtl.setText(_translate("BGBudgeterClass", "BG Budgeter - Income Settings"))
        self.incomeInfoLbl1.setText(_translate("BGBudgeterClass", "Income should include everything you wish to include in your budget, e.g. salary, loans, side income and even interest if you wish"))
        self.incomePeriodComboBox.setItemText(0, _translate("BGBudgeterClass", "Annually"))
        self.incomePeriodComboBox.setItemText(1, _translate("BGBudgeterClass", "Monthly"))
        self.incomePeriodComboBox.setItemText(2, _translate("BGBudgeterClass", "Weekly"))
        self.incomePeriodComboBox.setItemText(3, _translate("BGBudgeterClass", "Maintenance Loan (Total/year)"))
        self.removeButton.setText(_translate("BGBudgeterClass", "Remove"))
        self.addIncomeButton.setText(_translate("BGBudgeterClass", "Add income source"))
        self.updateIncomeButton.setText(_translate("BGBudgeterClass", "UPDATE"))
        self.backButtonIncomePage.setText(_translate("BGBudgeterClass", "BACK"))
        self.categoryTtl.setText(_translate("BGBudgeterClass", "BG Budgeter - Category Settings"))
        self.addCategoryButton.setText(_translate("BGBudgeterClass", "Add"))
        self.categoryTipsLbl.setText(_translate("BGBudgeterClass", "Tips:\n"
"- Any money you want to save per budget period should be included here\n"
"  as a separate category"))
        self.backButtonCategoryPage.setText(_translate("BGBudgeterClass", "BACK"))
        self.otherOptionsTtl.setText(_translate("BGBudgeterClass", "BG Budgeter - Other Options"))
        self.backButtonOptionsPage.setText(_translate("BGBudgeterClass", "BACK"))
        self.otherOptionsTtl_2.setText(_translate("BGBudgeterClass", "BG Budgeter - Other Options"))
        self.backButtonViewBudgetPage.setText(_translate("BGBudgeterClass", "BACK"))
import BGBudgeter_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BGBudgeterClass = QtWidgets.QMainWindow()
    ui = Ui_BGBudgeterClass()
    ui.setupUi(BGBudgeterClass)
    BGBudgeterClass.show()
    sys.exit(app.exec_())
